<?php

use \Hametuha\HamPay\Pattern\UnitTest;

class GmoCcTest extends UnitTest
{

    protected $order_id = '';

    protected $member_id = '';

    protected $access_key = '';

    protected $access_pass = '';

    protected $card_seq = false;

    /**
     * Set up test suite
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->order_id = 'tran-' . time();
        $this->member_id = 'member-'.time();
    }


    public function testCreditCard()
    {
        // Execution
        $auth = \Hametuha\HamPay\Service\GMO\Operation\CC\ExecTran::exec([
            'OrderID' => $this->order_id,
            'Method' => \Hametuha\HamPay\Service\GMO\Method::IKKATU,
            'JobCd' => \Hametuha\HamPay\Service\GMO\JobCode::AUTH,
            'Amount' => 1000,
            'CardNo' => '4111111111111111',
            'Expire' => '1901',
            'SecurityCode' => '123',
        ]);
        // Assertion
        $this->assertArrayHasKey('AccessID', $auth);
        $this->assertArrayHasKey('AccessPass', $auth);
        $this->assertArrayHasKey('OrderID', $auth);
        $this->assertEquals($this->order_id, $auth['OrderID']);
        $this->assertArrayHasKey('Forward', $auth);
        $this->assertArrayHasKey('Approve', $auth);
        $this->assertArrayHasKey('TranID', $auth);
        $this->assertArrayHasKey('TranDate', $auth);
        $this->assertArrayHasKey('CheckString', $auth);
        // Save access key
        $this->access_key = $auth['AccessID'];
        $this->access_pass = $auth['AccessPass'];
    }

    /**
     * @depends testCreditCard
     */
    public function testSaveMember()
    {
        // Save member
        $member = \Hametuha\HamPay\Service\GMO\Operation\CC\SaveMember::exec([
            'MemberID' => $this->member_id,
            'MemberName' => 'TestUser',
        ]);
        // Assertion
        $this->assertEquals($this->member_id, $member['MemberID']);
    }

    /**
     * @depends testSaveMember
     */
    public function testSaveCard()
    {
        // Save Credit card
        $card = \Hametuha\HamPay\Service\GMO\Operation\CC\SaveTradedCard::exec([
            'OrderID' => $this->order_id,
            'MemberID' => $this->member_id,
        ]);
        // Assertion
        $this->assertArrayHasKey('CardSeq', $card);
        $this->assertArrayHasKey('CardNo', $card);
        $this->assertArrayHasKey('Forward', $card);
        // Save card sequence
        $this->card_seq = $card['CardSeq'];
    }

    /**
     * @depends testSaveCard
     */
    public function testExistence()
    {
        // Check card exitence
        $card = \Hametuha\HamPay\Service\GMO\Operation\CC\SearchCard::exec([
            'MemberID' => $this->member_id,
            'SeqMode' => 0,
            'CardSeq' => $this->card_seq,
        ]);
        // Assertion
        $this->assertEquals($this->card_seq, $card['CardSeq']);
        // Delete Card
        $result = \Hametuha\HamPay\Service\GMO\Operation\CC\DeleteCard::exec([
            'MemberID' => $this->member_id,
            'CardSeq' => $this->card_seq,
        ]);
        // Assertion
        $this->assertEquals($this->card_seq, $result['CardSeq']);
        // Delete member
        $member = \Hametuha\HamPay\Service\GMO\Operation\CC\DeleteMember::exec([
            'MemberID' => $this->member_id,
        ]);
        // Assertion
        $this->assertEquals($this->member_id, $member['MemberID']);
    }
}
